Add Etherscan link to txn sim > details > contract
rainbow-me/browser-extension pull request #1314
Opened 2024-01-22 21:58 UTC by BrodyHughes

Fixes BX-####
Figma link (if any):

## What changed (plus any additional context for devs)

## Screen recordings / screenshots

## What to test

2024-01-22 22:47 UTC, DanielSinclair requested changes

2024-01-22 22:47 UTC, DanielSinclair commented on src/entries/popup/components/AddressDisplay.tsx
> +            }
To support other explorer, we'll want to make this generic. We get explorer URLs upstream from `viem/chains` and you can reference this from the Activity right-click https://github.com/rainbow-me/browser-extension/blob/35e3739098267fab82e67f896719befd156caca1/src/entries/popup/pages/home/Activity/ActivityContextMenu.tsx#L46

2024-01-22 22:47 UTC, DanielSinclair commented on static/json/languages/en_US.json
> +      "view_on_etherscan": "View on Etherscan",
I'd use the key `view_on_explorer` for consistency and accept the explorer name (i.e. Etherscan vs Arbiscan)

2024-01-23 22:38 UTC, DanielSinclair approved these changes

2024-01-23 22:39 UTC, DanielSinclair commented
Looks good to me!

2024-01-24 18:08 UTC, brunobar79 approved these changes
💯

2024-01-24 21:06 UTC, merged