fix: upgrade swap sdk for Blast and Zora support
rainbow-me/browser-extension pull request #1448
Opened 2024-04-01 18:13 UTC by DanielSinclair

Fixes BX-####
Figma link (if any):

## What changed (plus any additional context for devs)
- upgraded `@rainbow-me/swaps` to `0.13.0`

## Screen recordings / screenshots

## What to test

2024-04-02 02:25 UTC, greg-schrammel commented on src/core/state/favorites/index.ts
> +        } else if (version === 2) {
no way I had to click "submit review" to send the comments my bad

2024-04-02 17:08 UTC, welps approved these changes

2024-04-02 18:19 UTC, estebanmino commented on src/core/state/favorites/index.ts
> +        } else if (version === 2) {
right

2024-04-02 21:03 UTC, welps requested changes
hold bc zora swaps are not working here

2024-04-03 16:37 UTC, welps approved these changes

2024-04-03 17:41 UTC, merged