Add `Rootstock` network
rainbow-me/browser-extension pull request #1506
Opened 2024-04-18 14:29 UTC by ahsan-javaiid

### Description
This PR adds `rootstock` network to the rainbow wallet. Rootstock is bitcoin sidechain with full compatibility with ethereum.

Website: https://rootstock.io
Defillama: https://defillama.com/chain/Rootstock
Explorer: https://explorer.rootstock.io
Developer portal: https://dev.rootstock.io 

### Demo
<img width="359" alt="Screenshot 2024-04-18 at 7 02 36 PM" src="https://github.com/rainbow-me/browser-extension/assets/104683677/65cbfc6d-c266-435b-b918-24751f023795">
<img width="356" alt="Screenshot 2024-04-18 at 7 04 17 PM" src="https://github.com/rainbow-me/browser-extension/assets/104683677/271d7ecc-d1f9-4e0b-bc51-0156cffb6171">
<img width="353" alt="Screenshot 2024-04-18 at 7 05 03 PM" src="https://github.com/rainbow-me/browser-extension/assets/104683677/7b9ec5cb-451f-40c2-85ba-4124d367624d">
<img width="352" alt="Screenshot 2024-04-18 at 7 04 48 PM" src="https://github.com/rainbow-me/browser-extension/assets/104683677/5f3510c5-f319-4525-960a-c1b3ecaca969">
<img width="352" alt="Screenshot 2024-04-18 at 7 03 32 PM" src="https://github.com/rainbow-me/browser-extension/assets/104683677/9e61bced-f88f-4d6b-b2cf-3e68821bb7b0">
<img width="352" alt="Screenshot 2024-04-18 at 7 02 51 PM" src="https://github.com/rainbow-me/browser-extension/assets/104683677/760d2575-68ed-4bd6-b7b1-ce13383f2db0">

### Testing
- Rootstock network
- Send / Receive RBTC
- See balance of RBTC and ERC20 Tokens

2024-04-18 14:33 UTC, ahsan-javaiid commented
cc: @brunobar79 @derHowie @DanielSinclair @estebanmino review. Feel free to let me know if anything needs to be changes. Looking forward to adding Rootstock in rainbow.

2024-04-18 19:41 UTC, DanielSinclair requested changes
Hello! This unfortunately won't add full support for the network as it is only touching on the frontend pieces. Instead, please revert these changes, and add Rootstock mainnet alongside the testnet to add it to our Add Network flow.

2024-04-18 19:41 UTC, DanielSinclair commented on src/entries/popup/pages/settings/customChain/index.tsx
Please add Rootstock mainnet here

2024-04-19 00:36 UTC, ahsan-javaiid commented on src/entries/popup/pages/settings/customChain/index.tsx
Thank you @DanielSinclair for the reviewing this PR. I would like to ask a quick question:
I am looking to add `Rootstock` as a rainbow supported network in wallet. That's why i added all these changes to add Rootstock network in the list of available rainbow supported networks.   

I know we can add it as custom network as you suggested. 

Asking, if you can please consider this request to add Rootstock as rainbow supported network and i can do any further changes requested.

I will look forward to your thoughts.

2024-04-19 00:54 UTC, DanielSinclair commented on src/entries/popup/pages/settings/customChain/index.tsx
@ahsan-javaiid That unfortunately won't be possible as we require significant demand and vendor support before we can roll out support for any particular chain as a "first class" network. You can however add chain information to our Add Network flow to make it easier for users to add that network.

2024-04-19 03:37 UTC, ahsan-javaiid commented on src/entries/popup/pages/settings/customChain/index.tsx
Hi @DanielSinclair 

Please share your telegram id. I will connect you and your team with Rootstock to provide full vendor support and meet the other significant demands. We can discuss rest of the requirements there and start working on adding as "first class" network into rainbow. 

I would be thankful to you.

2024-04-19 03:48 UTC, DanielSinclair commented on src/entries/popup/pages/settings/customChain/index.tsx
@ahsan-javaiid Prospective chains can email `partnerships@rainbow.me`, but the better option will be to revert some of the changes here and add the mainnet chain to our Add Network flow.

2024-04-19 21:23 UTC, DanielSinclair commented
Closing in favor of #1508

2024-04-19 21:23 UTC, closed without merging

2024-05-02 17:37 UTC, ahsan-javaiid commented on src/entries/popup/pages/settings/customChain/index.tsx
Hi @DanielSinclair
Hope you are doing well.
Thanks for adding Rootstock as custom network and making a release last time.
Would be great to hear back on partnership email sent on `partnerships@rainbow.me` sent by Rootstock team. 
Thank you.

2024-05-21 13:04 UTC, ahsan-javaiid commented on src/entries/popup/pages/settings/customChain/index.tsx
@@DanielSinclair Any thought's on partnership here to complete the full integration. Would be happy to connect and discuss. Hope to hear back from your side. 🙂

2024-06-06 07:58 UTC, ahsan-javaiid commented on src/entries/popup/pages/settings/customChain/index.tsx
@DanielSinclair Any reply on partnership email. Hope to hear back from your side. 

Visit Rootstock network stats: https://defillama.com/chain/Rootstock
Website: https://rootstock.io/
Explorer: https://explorer.rootstock.io/
Developer portal: https://dev.rootstock.io/