fix: BX-1582
rainbow-me/browser-extension pull request #1647
Opened 2024-07-30 18:47 UTC by estebanmino

Fixes BX-####
Figma link (if any):

## What changed (plus any additional context for devs)

## Screen recordings / screenshots

## What to test

2024-07-30 18:48 UTC, estebanmino commented on src/entries/background/handlers/handleProviderRequest.ts
> +          (chain: Chain) => chain.rpcUrls.default.http[0] === rpcUrl,
checking if the rpcurl was added before, so we don't set it as active

2024-07-30 18:49 UTC, estebanmino commented on src/entries/popup/pages/settings/rpcs.tsx
> +                        chain.rpcUrls.default.http[0]
the logic we had here was disabling the option to remove the rpc url of rainbow supported chains, now we'll only block the removal of the rainbow rpc

2024-07-30 19:05 UTC, magiziz approved these changes

2024-07-31 06:33 UTC, DanielSinclair requested changes
Spotted a few issues:
- Noticed that the network toggle will flip to disable when removing a 2nd RPC (I suppose the duplicate RPC URLs match so the network will get caught in a check based on that logic).
- It seems like we can remove the testnet RPCs now as well; any way to limit that?

Tested against Zora and didn't see a new duplicate get added after I cleared that network 👍 

I do see duplicates across other networks as well. Should we do another migration to clear out those duplicates once this logic change is settled?
<img width="356" alt="Screenshot 2024-07-31 at 2 32 45 AM" src="https://github.com/user-attachments/assets/da276232-9b5d-41a4-a32e-cf38802e83e8">

2024-07-31 18:59 UTC, estebanmino commented
@DanielSinclair how did you get those duplicated networks? i don't have any

2024-07-31 19:10 UTC, estebanmino commented
@DanielSinclair i also fixed those issues you mentioned with these changes, they're are currently in prod

2024-08-01 19:31 UTC, DanielSinclair approved these changes
@estebanmino Changes lgtm. I'm not quite sure where the duplicates came from. I have them on my internal build but not prod, so it must have been one of the migrations; not sure if it impacts prod in other scenarios.

2024-08-02 15:40 UTC, merged