swap seach popular in rainbow
rainbow-me/browser-extension pull request #1696
Opened 2024-09-09 17:08 UTC by greg-schrammel

Fixes BX-####
Figma link (if any):

## What changed (plus any additional context for devs)

## Screen recordings / screenshots

## What to test

2024-09-09 21:11 UTC, greg-schrammel commented on src/core/resources/search/tokenSearch.ts
> -        ].includes(`${a.uniqueId}_${chainId}`),
replaced this with `isNativeAsset` from `~/core/utils/chains`, fixes some chains like degen that was not getting the right native

2024-09-10 17:10 UTC, estebanmino approved these changes
lgtm

2024-09-13 17:29 UTC, benisgold requested changes

2024-09-13 17:29 UTC, benisgold commented on src/entries/popup/hooks/useSearchCurrencyLists.ts
> +    if (popularAssets) {
i think you need to make sure there is no overlap between assets in the popular section and assets in other sections. here's the app logic https://github.com/rainbow-me/rainbow/blob/develop/src/__swaps__/screens/Swap/hooks/useSearchCurrencyLists.ts

lmk if you want me to explain more

2024-10-03 15:53 UTC, greg-schrammel commented on src/core/state/favorites/index.ts
> +  POL_POLYGON_ADDRESS,
eslint sort imports rule

2024-10-03 16:18 UTC, greg-schrammel commented on src/entries/popup/hooks/useSearchCurrencyLists.ts
> +}
made a more generic function to filter the sections, took the name from [new Set().difference()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/difference)

this changes for example 
```ts
filterAssetsFromBridgeAndAssetToSell(sectionAssets)
``` 
for 
```ts
difference(sectionAssets, [bridgeAsset, assetToSell])
```

I think its more extensible and easier to understand the intention

2024-10-05 03:21 UTC, DanielSinclair approved these changes
Functionality looks good to me

2024-10-05 03:38 UTC, merged